name: Release helm chart
on:
  push:
    branches:
      - release-*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      APP_VERSION: 1.0.6
      VERSION: 0.0.2

    steps:
      - name: 
        uses: actions/checkout@v2
      
      - uses: azure/setup-helm@v1
        with:
          version: 'latest' # default is latest stable
        id: install

      - name: Helm Package
        run: |
          helm package deploy/kubernetes/helm  -d ~/helm/repo --app-version ${{ env.APP_VERSION }} --version ${{ env.VERSION  }}
          helm repo index ~/helm/repo --url ${{ secrets.DONGTAI_IAST_CHART_REPO_URL }}

      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.CHART_OSS_ENDPOINT }}
          access-key-id: ${{ secrets.CHART_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.CHART_OSS_ACCESS_KEY_SECRET }}
      - run: |
          ossutil cp ~/helm/repo/dongtai-iast-${{ env.VERSION  }}.tgz  oss://dongtai-helm-charts/iast/
          ossutil cp -rf ~/helm/repo/index.yaml  oss://dongtai-helm-charts/iast/

          
